# Generated by Django 5.2.5 on 2025-08-20 14:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_type', models.CharField(choices=[('SICK_LEAVE', 'Sick Leave'), ('EMERGENCY_LEAVE', 'Emergency Leave'), ('PERSONAL_LEAVE', 'Personal Leave'), ('MEDICAL_APPOINTMENT', 'Medical Appointment'), ('FAMILY_EMERGENCY', 'Family Emergency'), ('ACADEMIC_RELATED', 'Academic Related'), ('OFFICIAL_DUTY', 'Official Duty'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.PositiveIntegerField(help_text='Number of days requested', validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField(help_text='Detailed reason for permission request')),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('residential_address', models.TextField()),
                ('supervisor_endorsed', models.BooleanField(default=False)),
                ('supervisor_endorsed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_comments', models.TextField(blank=True)),
                ('days_granted', models.PositiveIntegerField(blank=True, help_text='Number of days granted by HR', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('granted_start_date', models.DateField(blank=True, null=True)),
                ('granted_end_date', models.DateField(blank=True, null=True)),
                ('resumption_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUPERVISOR_APPROVED', 'Approved by Supervisor'), ('HR_REVIEW', 'Under HR Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('hr_decision_date', models.DateTimeField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, help_text='Medical certificate, invitation letter, etc.', null=True, upload_to='permission_documents/%Y/%m/')),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_retroactive', models.BooleanField(default=False, help_text='Request submitted after the fact')),
                ('hr_officer', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'HR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_permission_requests', to=settings.AUTH_USER_MODEL)),
                ('nsp', models.ForeignKey(limit_choices_to={'user_type': 'NSP'}, on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_permission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Request',
                'verbose_name_plural': 'Permission Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('SUBMITTED', 'Request Submitted'), ('SUPERVISOR_APPROVED', 'Supervisor Approved'), ('HR_APPROVED', 'HR Approved'), ('DECLINED', 'Request Declined'), ('REMINDER', 'Reminder'), ('RESUMPTION', 'Resumption Reminder')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message_body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('permission_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='permissions.permissionrequest')),
            ],
            options={
                'verbose_name': 'Permission Email Notification',
                'verbose_name_plural': 'Permission Email Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('color', models.CharField(default='#3788d8', max_length=7)),
                ('remind_before_days', models.PositiveIntegerField(default=1)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('permission_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entry', to='permissions.permissionrequest')),
            ],
            options={
                'verbose_name': 'Permission Calendar Entry',
                'verbose_name_plural': 'Permission Calendar Entries',
            },
        ),
        migrations.CreateModel(
            name='PermissionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('approved_requests', models.PositiveIntegerField(default=0)),
                ('declined_requests', models.PositiveIntegerField(default=0)),
                ('pending_requests', models.PositiveIntegerField(default=0)),
                ('total_days_requested', models.PositiveIntegerField(default=0)),
                ('total_days_granted', models.PositiveIntegerField(default=0)),
                ('avg_processing_time_hours', models.FloatField(blank=True, null=True)),
                ('nsp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Statistics',
                'verbose_name_plural': 'Permission Statistics',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PermissionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permission_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='permissions.permissionrequest')),
            ],
            options={
                'verbose_name': 'Permission Status History',
                'verbose_name_plural': 'Permission Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('permission_type', models.CharField(choices=[('SICK_LEAVE', 'Sick Leave'), ('EMERGENCY_LEAVE', 'Emergency Leave'), ('PERSONAL_LEAVE', 'Personal Leave'), ('MEDICAL_APPOINTMENT', 'Medical Appointment'), ('FAMILY_EMERGENCY', 'Family Emergency'), ('ACADEMIC_RELATED', 'Academic Related'), ('OFFICIAL_DUTY', 'Official Duty'), ('OTHER', 'Other')], max_length=20)),
                ('default_reason', models.TextField()),
                ('default_duration_days', models.PositiveIntegerField()),
                ('requires_document', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_approve_if_days_less_than', models.PositiveIntegerField(blank=True, help_text='Auto-approve if request is for less than this many days', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Template',
                'verbose_name_plural': 'Permission Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='permissionrequest',
            index=models.Index(fields=['nsp', 'status', '-created_at'], name='permissions_nsp_id_fd47e2_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionrequest',
            index=models.Index(fields=['supervisor', 'status'], name='permissions_supervi_ac1086_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionrequest',
            index=models.Index(fields=['status', '-created_at'], name='permissions_status_865085_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionstatistics',
            unique_together={('year', 'month', 'department', 'nsp')},
        ),
    ]
