# Generated by Django 5.2.5 on 2025-08-20 14:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('nss_id', models.CharField(max_length=50, unique=True)),
                ('program', models.CharField(choices=[('REGULAR', 'Regular National Service'), ('TEACHERS', 'Teachers National Service'), ('HEALTH', 'Health National Service'), ('GRADUATE', 'Graduate National Service')], max_length=20)),
                ('service_year', models.PositiveIntegerField()),
                ('institution_attended', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('course_of_study', models.CharField(max_length=100)),
                ('nss_appointment_letter', models.FileField(upload_to='nss_submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('REQUIRES_INFO', 'Requires Additional Information')], default='PENDING', max_length=20)),
                ('submission_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_submission', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'HR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Submission',
                'verbose_name_plural': 'Appointment Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('appointment_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointmentsubmission')),
            ],
            options={
                'verbose_name': 'Appointment Status History',
                'verbose_name_plural': 'Appointment Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('CONFIRMATION', 'Submission Confirmation'), ('APPROVAL', 'Approval Notification'), ('REJECTION', 'Rejection Notification'), ('CREDENTIALS', 'Login Credentials'), ('REMINDER', 'Reminder Email'), ('DOCUMENT_REQUEST', 'Document Request')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message_body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('appointment_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='appointments.appointmentsubmission')),
            ],
            options={
                'verbose_name': 'Appointment Email Log',
                'verbose_name_plural': 'Appointment Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GNPCAppointmentLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('reporting_date', models.DateField()),
                ('department_assigned', models.CharField(max_length=100)),
                ('service_start_date', models.DateField()),
                ('service_end_date', models.DateField()),
                ('letter_content', models.TextField(help_text='Generated letter content')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True)),
                ('pdf_letter', models.FileField(blank=True, null=True, upload_to='gnpc_letters/%Y/')),
                ('is_issued', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('nsp_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gnpc_appointment_letter', to='accounts.nspprofile')),
                ('signed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'HR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_appointment_letters', to=settings.AUTH_USER_MODEL)),
                ('supervisor_assigned', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointment_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GNPC Appointment Letter',
                'verbose_name_plural': 'GNPC Appointment Letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('VERIFICATION', 'Verification Document'), ('AMENDMENT', 'Amendment Letter'), ('EXTENSION', 'Service Extension'), ('TERMINATION', 'Service Termination'), ('CERTIFICATE', 'Completion Certificate')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='appointment_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('is_required', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_appointment_docs', to=settings.AUTH_USER_MODEL)),
                ('appointment_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='appointments.appointmentsubmission')),
                ('gnpc_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='appointments.gnpcappointmentletter')),
            ],
            options={
                'verbose_name': 'Appointment Document',
                'verbose_name_plural': 'Appointment Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentsubmission',
            index=models.Index(fields=['status', '-created_at'], name='appointment_status_208783_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentsubmission',
            index=models.Index(fields=['email'], name='appointment_email_557110_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentsubmission',
            index=models.Index(fields=['nss_id'], name='appointment_nss_id_40bd67_idx'),
        ),
    ]
