# Generated by Django 5.2.5 on 2025-08-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdocument',
            name='gnpc_letter',
        ),
        migrations.DeleteModel(
            name='GNPCAppointmentLetter',
        ),
    ]
