# Generated by Django 5.2.5 on 2025-08-20 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('report_year', models.PositiveIntegerField()),
                ('activities_undertaken', models.TextField(help_text='Detailed description of activities undertaken during the month')),
                ('achievements', models.TextField(help_text='Key achievements and accomplishments')),
                ('challenges_faced', models.TextField(blank=True, help_text='Challenges encountered and how they were addressed')),
                ('skills_acquired', models.TextField(blank=True, help_text='New skills or knowledge acquired')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('total_working_days', models.PositiveIntegerField()),
                ('days_present', models.PositiveIntegerField()),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('days_on_permission', models.PositiveIntegerField(default=0)),
                ('self_rating', models.PositiveIntegerField(help_text='Self-rating on performance (1-5 scale)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_comments', models.TextField(blank=True)),
                ('supporting_documents', models.FileField(blank=True, help_text='Supporting documents, photos, or evidence', null=True, upload_to='monthly_reports/%Y/%m/')),
                ('nsp', models.ForeignKey(limit_choices_to={'user_type': 'NSP'}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-report_year', '-report_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_type', models.CharField(choices=[('MONTHLY', 'Monthly Evaluation'), ('QUARTERLY', 'Quarterly Evaluation'), ('MID_TERM', 'Mid-term Evaluation'), ('FINAL', 'Final Evaluation')], max_length=20)),
                ('evaluation_period_start', models.DateField()),
                ('evaluation_period_end', models.DateField()),
                ('punctuality', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('attendance', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('work_quality', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('initiative', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('teamwork', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('communication', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('learning_ability', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('professionalism', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('overall_rating', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('strengths', models.TextField(help_text='Key strengths observed')),
                ('areas_for_improvement', models.TextField(help_text='Areas that need improvement')),
                ('recommendations', models.TextField(help_text='Recommendations for development')),
                ('future_assignments', models.TextField(blank=True, help_text='Recommended future assignments or projects')),
                ('goals_achieved', models.TextField(blank=True, help_text='Goals achieved during the evaluation period')),
                ('goals_for_next_period', models.TextField(blank=True, help_text='Goals for the next evaluation period')),
                ('nsp_comments', models.TextField(blank=True, help_text="NSP's response to the evaluation")),
                ('nsp_acknowledged', models.BooleanField(default=False)),
                ('nsp_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('hr_reviewed', models.BooleanField(default=False)),
                ('hr_comments', models.TextField(blank=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_reviewer', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'HR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_evaluations', to=settings.AUTH_USER_MODEL)),
                ('nsp', models.ForeignKey(limit_choices_to={'user_type': 'NSP'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'user_type': 'SUPERVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Evaluation',
                'verbose_name_plural': 'Performance Evaluations',
                'ordering': ['-evaluation_period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('total_reports_due', models.PositiveIntegerField(default=0)),
                ('reports_submitted', models.PositiveIntegerField(default=0)),
                ('reports_approved', models.PositiveIntegerField(default=0)),
                ('reports_rejected', models.PositiveIntegerField(default=0)),
                ('reports_pending', models.PositiveIntegerField(default=0)),
                ('evaluations_completed', models.PositiveIntegerField(default=0)),
                ('average_performance_rating', models.FloatField(blank=True, null=True)),
                ('on_time_submissions', models.PositiveIntegerField(default=0)),
                ('late_submissions', models.PositiveIntegerField(default=0)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Statistics',
                'verbose_name_plural': 'Report Statistics',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_history', to='reports.performanceevaluation')),
                ('monthly_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_history', to='reports.monthlyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Submission History',
                'verbose_name_plural': 'Report Submission Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('MONTHLY_REPORT', 'Monthly Report'), ('EVALUATION', 'Performance Evaluation'), ('INCIDENT_REPORT', 'Incident Report'), ('PROJECT_REPORT', 'Project Report')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sections', models.JSONField(default=list, help_text='List of sections and their requirements')),
                ('required_fields', models.JSONField(default=list, help_text='List of required fields')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['nsp', 'status'], name='reports_mon_nsp_id_51d647_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['supervisor', 'status'], name='reports_mon_supervi_fb5efb_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['report_year', 'report_month'], name='reports_mon_report__4335ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('nsp', 'report_month', 'report_year')},
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['nsp', '-evaluation_period_end'], name='reports_per_nsp_id_28e33c_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['supervisor', '-evaluation_period_end'], name='reports_per_supervi_9b0874_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportstatistics',
            unique_together={('year', 'month', 'department', 'supervisor')},
        ),
    ]
